default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: qui_veut_gagner_des_bv_db_development
  username: deploy
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

test:
  <<: *default
  database: qui_veut_gagner_des_bv_db_test
  username: deploy
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  database: qui_veut_gagner_des_bv_db_production
  username: deploy
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
